services:
  - type: web
    name: shmedium
    env: python
    region: oregon
    plan: free
    branch: portfolio-deploy
    buildCommand: |
      npm install --prefix react-app
      NODE_OPTIONS=--openssl-legacy-provider npm run build --prefix react-app
      pip install -r requirements.txt
      pip install psycopg2-binary
      flask db upgrade
      flask seed all
    startCommand: gunicorn app:app
    healthCheckPath: /api/docs
    autoDeploy: true
    envVars:
      - key: FLASK_APP
        value: app
      - key: FLASK_ENV
        value: production
      - key: SCHEMA
        value: shmedium_schema
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_BUCKET_NAME
        value: shmedium-prod-images-dcrader
      - key: AWS_REGION
        value: us-west-1
